use_frameworks!

target 'SwiftyFormat_Example' do
  pod 'SwiftyFormat', :path => '../'

  target 'SwiftyFormat_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
